import { BG_COLORS_SAMPLE } from "./constants";

export const TEMPLATES = [
  {
    name: "creator.bst",
    title: "Creative Hub",
    subtitle: "Unleashing Creativity",
    avatar: "https://i.seadn.io/gae/miB3_jXJ2EfvYO-SaWyxTDQgp0p_5Z5GrpiRSZ_HfWdUCCG4aF6DchiEKm3Fh84oRRkTQYC_gXy2mp0fHx_eqFfKflWQuSskk9b3?w=500&auto=format",
    bio: "Welcome to my creative world. Follow my journey as I share my work and passion!",
    links: [
      // {
      //   type: "simple link",
      //   title: "Portfolio",
      //   url: "https://yourlink.com",
      //   image: "",
      //   content: "",
      //   styles: {
      //     icon: "RiBrushFill",
      //     size: "md",
      //     order: 0,
      //   },
      // },
      // {
      //   type: "simple link",
      //   title: "Blog",
      //   url: "https://blog.yourlink.com",
      //   image: "",
      //   content: "",
      //   styles: {
      //     icon: "RiBookFill",
      //     size: "md",
      //     order: 1,
      //   },
      // },
      // {
      //   type: "image link",
      //   title: "Inspiration Board",
      //   url: "https://pinterest.com/exampleuser",
      //   image: "https://yourlink.com/inspiration.png",
      //   content: "",
      //   styles: {
      //     size: "sm",
      //     order: 2,
      //   },
      // },
    ],
    wallets: {
      ETH: "0xBFd210db795A9Ac48D0C3be2a74232BE44144E84",
      Polygon: "0xBFd210db795A9Ac48D0C3be2a74232BE44144E84",
    },
    socials: {
      "xyz.farcaster": "https://farcaster.com/exampleuser",
      "com.instagram": "https://www.instagram.com/exampleuser",
      "com.google.youtube": "https://www.youtube.com/@exampleuser",
      "com.twitter": "https://twitter.com/exampleuser",
    },
    styles: {
      lightMode: true,
      bgColor:'linear-gradient(180deg, #FF7E5F 0%, #FEB47B 100%)',
      avatarShape: "hex",
      buttonBgColor: "orange",
      font: "Playfair Display",
      round: "full",
      variant: "pop",
    },
  },
  {
    name: "web3enthusiast.bst",
    title: "Web3 Explorer",
    subtitle: "Navigating the Decentralized World",
    avatar: "https://i.seadn.io/gae/byqI5_6HfQBm9yX0LmnM_1Jj_4rF5gQj6RRRNYVp6gO0wGOKInC4woI-knidpdHOLz8HTCOl2he7T_udykzOJbDXUQqAjpoQaE5L?w=500&auto=format",
    bio: "Connecting people and communities across the Web3 ecosystem",
    links: [
      // {
      //   type: "simple link",
      //   title: "My Web3 Blog",
      //   url: "https://web3blog.yourlink.com",
      //   image: "",
      //   content: "",
      //   styles: {
      //     icon: "RiBankFill",
      //     size: "md",
      //     order: 0,
      //   },
      // },
      // {
      //   type: "twitter timeline",
      //   title: "Latest Tweets",
      //   url: "https://twitter.com/exampleuser",
      //   image: "",
      //   content: "",
      //   styles: {
      //     icon: "RiTwitterFill",
      //     size: "md",
      //     order: 1,
      //   },
      // },
      // {
      //   type: "nft gallery",
      //   title: "NFT Collection",
      //   url: "https://opensea.io/exampleuser",
      //   image: "https://yourlink.com/nft-collection.png",
      //   content: "",
      //   styles: {
      //     size: "sm",
      //     order: 2,
      //   },
      // },
    ],
    wallets: {
      ETH: "0xBFd210db795A9Ac48D0C3be2a74232BE44144E84",
      Polygon: "0xBFd210db795A9Ac48D0C3be2a74232BE44144E84",
      Base: "0xBFd210db795A9Ac48D0C3be2a74232BE44144E84",
    },
    socials: {
      "com.linkedin": "https://linkedin.com/in/exampleuser",
      "xyz.farcaster": "https://farcaster.com/exampleuser",
      "com.discord": "https://discord.gg/exampleuser",
      "org.telegram": "https://t.me/exampleuser",
    },
    styles: {
      lightMode: false,
      bgColor: '#1B262C',
      avatarShape: "circle",
      buttonBgColor: "blue",
      font: "DM Sans",
      round: "md",
      variant: "solid",
    },
  },
  {
    name: "cryptotrader.bst",
    title: "Crypto Trader",
    subtitle: "Buy Low, Sell High",
    avatar: "https://i.seadn.io/gae/dPkelxI8TIkqKc1JY6-vWwDZfr3LamwAPj5_eaPCrUWF3-NTBbfWu6XOhl8e_vaAmncWkwxEHNBwzEGCFdZHZnYd?w=500&auto=format",
    bio: "Daily updates and trading insights. Follow along for market moves and strategies!",
    links: [
      {
        type: "simple link",
        title: "Trading Blog",
        url: "https://www.tradingview.com/u/Xanrox/",
        image: "",
        content: "",
        styles: {
          icon: "RiStockFill",
          size: "md",
          order: 0,
        },
      },
      {
        type: "payment button",
        title: "Support My Work",
        url: "",
        image: "",
        content: "Thank you, Your support keeps this page going!",
        styles: {
          size: "md",
          eth: "0xBFd210db795A9Ac48D0C3be2a74232BE44144E84",
          order: 2,
        },
      },
    ],
    wallets: {
      BTC: "bc1qpvsvcfzvz59h02hcuvc8y8jj385r2mlhnkt654",
      ETH: "0xBFd210db795A9Ac48D0C3be2a74232BE44144E84",
    },
    socials: {
      "org.telegram": "https://t.me/exampleuser",
      "com.twitter": "https://twitter.com/exampleuser",
      "xyz.farcaster": "https://farcaster.com/exampleuser",
      "com.medium": "https://medium.com/@exampleuser",
    },
    styles: {
      lightMode: false,
      bgColor: "linear-gradient(180deg, #0F2027 0%, #203A43 50%, #2C5364 100%)",
      avatarShape: "round",
      buttonBgColor: "red",
      font: "Audiowide",
      avatarSize:'md',
      headerColor: "#12121212",
      headerMode: true,
      round: "none",
      variant: "solid",
    },
  },
  {
    name: "freelancer.bst",
    title: "Freelance Designer",
    subtitle: "Bringing Ideas to Life",
    avatar: "https://i.seadn.io/gae/Fj1U-NBJ1zfHd54WxVhnoqhnWpUqLYAgomVYcm6Rbe_KOVnNpV0LHxWfNPQvKjQoHGAOvbDRdrsVqXpYCxh-qadYrL7ioMSMNPYPbTU?w=500&auto=format",
    bio: "Freelance graphic designer specializing in branding, UX/UI, and illustrations",
    links: [
      {
        type: "pdf document",
        title: "Resume",
        url: "https://ipfs.io/ipfs/QmRDe1vyhJo7c4AKkPLx4cYDjLV9XHYUT1b4W4Uwt4mR1g/sam_shariat_cv.pdf",
        image: "",
        content: "",
        styles: {
          icon: "RiFileList3Fill",
          size: "lg",
          popup:true,
          variant:'pop',
          type:'modal',
          order: 1,
        },
      },
      {
        type: "simple link",
        title: "Fiverr Profile",
        url: "https://www.fiverr.com/exampleuser",
        image: "",
        content: "",
        styles: {
          icon: "RiHandCoinFill",
          variant:'pop',
          size: "md",
          order: 2,
        },
      },
      {
        type: "embed",
        title: "Request for Proposal",
        url: "https://app.deform.cc/form/24a0743b-1792-4c8f-a9b9-59f5893646de/?page_number=0",
        image: "",
        content: "",
        styles: {
          type:'modal',
          size: "md",
          order: 3,
          variant: "pop"
        },
      },
      
    ],
    wallets: {
      ETH: "0xBFd210db795A9Ac48D0C3be2a74232BE44144E84",
      Polygon: "0xBFd210db795A9Ac48D0C3be2a74232BE44144E84",
    },
    socials: {
      "com.linkedin": "https://linkedin.com/in/exampleuser",
      "com.dribbble": "https://dribbble.com/exampleuser",
      "com.pinterest": "https://pinterest.com/exampleuser",
      "com.instagram": "https://www.instagram.com/exampleuser",
    },
    styles: {
      lightMode: true,
      bgColor: "linear-gradient(180deg, #2ECC71 0%, #27AE60 100%)",
      avatarShape: "round",
      buttonBgColor: "green",
      font: "Pixelify Sans",
      headerColor: "#12121212",
      headerMode: true,
      avatarSize: 'sm',
      round: "md",
      variant: "pop",
    },
  },
  {
    name: "gamer.bst",
    title: "Pro Gamer",
    subtitle: "Level Up",
    avatar: "https://i.seadn.io/gcs/files/f7ca105e01303e384c12d2aa3e716674.png?w=500&auto=format",
    bio: "Streaming my gaming adventures, tips, and epic highlights. Join me in the game!",
    links: [
      // {
      //   type: "simple link",
      //   title: "Twitch Channel",
      //   url: "https://www.twitch.tv/exampleuser",
      //   image: "",
      //   content: "",
      //   styles: {
      //     icon: "RiTwitchFill",
      //     size: "md",
      //     order: 0,
      //   },
      // },
      // {
      //   type: "youtube video",
      //   title: "Latest Highlights",
      //   url: "https://youtu.be/gamehighlightvideo",
      //   image: "",
      //   content: "",
      //   styles: {
      //     icon: "RiYoutubeFill",
      //     size: "md",
      //     order: 1,
      //   },
      // },
      // {
      //   type: "simple link",
      //   title: "Game Store",
      //   url: "https://store.steampowered.com",
      //   image: "",
      //   content: "",
      //   styles: {
      //     icon: "RiGamepadFill",
      //     size: "md",
      //     order: 2,
      //   },
      // },
      // {
      //   type: "nft gallery",
      //   title: "Gaming NFT Collection",
      //   url: "https://opensea.io/gamingnfts",
      //   image: "",
      //   content: "",
      //   styles: {
      //     size: "sm",
      //     order: 3,
      //   },
      // },
    ],
    wallets: {
      ETH: "0xBFd210db795A9Ac48D0C3be2a74232BE44144E84",
      Polygon: "0xBFd210db795A9Ac48D0C3be2a74232BE44144E84",
    },
    socials: {
      "tv.twitch": "#",
      "com.google.youtube": "#",
      "com.discord": "#",
      "com.instagram": "#",
    },
    styles: {
      lightMode: false,
      bgColor: "linear-gradient(180deg, #141E30 0%, #243B55 100%)",
      avatarShape: "hex",
      buttonBgColor: "purple",
      font: "Luckiest Guy",
      round: "md",
      variant: "pop",
    },
  },
 
  {
    name: "developer.bst",
    title: "Web3 Developer",
    subtitle: "Building the Future of Web",
    avatar: "https://i.seadn.io/s/raw/files/e5f1b57169e993c02b38521770a3b52a.png?w=500&auto=formats",
    bio: "Experienced Web3 developer with a passion for dApps and blockchain innovation.",
    links: [
      {
        type: "simple link",
        title: "GitHub",
        url: "https://github.com/base-tree",
        image: "",
        content: "",
        styles: {
          icon: "RiGithubFill",
          variant: "border",
          size: "md",
          order: 0,
        },
      },
      {
        type: "simple link",
        title: "Portfolio",
        url: "https://github.com/sam-shariat",
        image: "",
        content: "",
        styles: {
          icon: "RiCodeSSlashFill",
          size: "md",
          order: 1,
          variant: "border"
        },
      }, 
      {
        type: "embed",
        title: "Project Demo",
        url: "https://basetree.xyz/base",
        image: "",
        content: "",
        styles: {
          type:'modal',
          size: "lg",
          order: 3,
          variant: "border"
        },
      },
    ],
    wallets: {
      ETH: "0xBFd210db795A9Ac48D0C3be2a74232BE44144E84",
      Polygon: "0xBFd210db795A9Ac48D0C3be2a74232BE44144E84",
      Solana: "BfiZDeHXzuz8pz5EGM6eUv1B1hLsGJQPRoxqYsBRKW3i",
    },
    socials: {
      "com.github": "https://github.com/exampleuser",
      "org.telegram": "https://t.me/exampleuser",
      "xyz.farcaster": "https://farcaster.com/exampleuser",
      "com.linkedin": "https://linkedin.com/in/exampleuser",
      "com.twitter": "https://twitter.com/exampleuser",
    },
    styles: {
      lightMode: false,
      bgColor: "linear-gradient(180deg, #1ABC9C 0%, #16A085 100%)",
      headerColor: "#648596",
      avatarShape: "round",
      buttonBgColor: "teal",
      font: "Space Mono",
      headerMode: true,
      avatarSize:'sm',
      round: "md",
      variant: "border",
    },
  },
  {
    name: "nftcollector.bst",
    title: "NFT Enthusiast",
    subtitle: "Collecting Digital Art & Assets",
    avatar: "https://i.seadn.io/gae/byqI5_6HfQBm9yX0LmnM_1Jj_4rF5gQj6RRRNYVp6gO0wGOKInC4woI-knidpdHOLz8HTCOl2he7T_udykzOJbDXUQqAjpoQaE5L?w=500&auto=format",
    bio: "Exploring the metaverse, collecting rare digital assets, and sharing my NFT journey!",
    links: [
      // {
      //   type: "nft gallery",
      //   title: "My NFT Collection",
      //   url: "https://opensea.io/exampleuser",
      //   image: "",
      //   content: "",
      //   styles: {
      //     size: "md",
      //     order: 0,
      //   },
      // },
      // {
      //   type: "simple link",
      //   title: "Metaverse Profile",
      //   url: "https://decentraland.org/exampleuser",
      //   image: "",
      //   content: "",
      //   styles: {
      //     icon: "RiLandscapeFill",
      //     size: "md",
      //     order: 1,
      //   },
      // },
      // {
      //   type: "tweet",
      //   title: "Latest NFT Acquisitions",
      //   url: "https://twitter.com/exampleuser/status/latesttweet",
      //   image: "",
      //   content: "",
      //   styles: {
      //     icon: "RiTwitterFill",
      //     size: "md",
      //     order: 2,
      //   },
      // },
      // {
      //   type: "donate button",
      //   title: "Support My NFT Journey",
      //   url: "",
      //   image: "",
      //   content: "Help me expand my NFT collection!",
      //   styles: {
      //     size: "md",
      //     eth: "0xBFd210db795A9Ac48D0C3be2a74232BE44144E84",
      //     order: 3,
      //   },
      // },
    ],
    wallets: {
      ETH: "0xBFd210db795A9Ac48D0C3be2a74232BE44144E84",
      Polygon: "0xBFd210db795A9Ac48D0C3be2a74232BE44144E84",
    },
    socials: {
      "com.twitter": "https://twitter.com/exampleuser",
      "com.instagram": "https://www.instagram.com/exampleuser",
      "com.opensea": "https://opensea.io/exampleuser",
    },
    styles: {
      lightMode: false,
      bgColor: "linear-gradient(180deg, #8E44AD 0%, #2C3E50 100%)",
      avatarShape: "round",
      buttonBgColor: "purple",
      font: "Audiowide",
      round: "full",
      variant: "border",
    },
  }
];
