export const TEMPLATES = [
  {
    name: "creator.bst",
    title: "Creative Hub",
    subtitle: "Unleashing Creativity",
    avatar: "https://yourlink.com/creator-avatar.png",
    bio: "Welcome to my creative world. Follow my journey as I share my work, passion, and inspirations!",
    links: [
      {
        type: "simple link",
        title: "Portfolio",
        url: "https://yourlink.com",
        image: "",
        content: "",
        styles: {
          icon: "RiBrushFill",
          size: "md",
          order: 0,
        },
      },
      {
        type: "simple link",
        title: "Blog",
        url: "https://blog.yourlink.com",
        image: "",
        content: "",
        styles: {
          icon: "RiBookFill",
          size: "md",
          order: 1,
        },
      },
      {
        type: "image link",
        title: "Inspiration Board",
        url: "https://pinterest.com/exampleuser",
        image: "https://yourlink.com/inspiration.png",
        content: "",
        styles: {
          size: "sm",
          order: 2,
        },
      },
    ],
    wallets: {
      ETH: "0xExampleWalletAddress",
      Polygon: "0xExampleWalletAddress",
    },
    socials: {
      "com.instagram": "https://www.instagram.com/exampleuser",
      "com.google.youtube": "https://www.youtube.com/@exampleuser",
      "com.twitter": "https://twitter.com/exampleuser",
    },
    styles: {
      lightMode: false,
      bgColor: "linear-gradient(180deg, #FF9F43 0%, #FF6F61 100%)",
      avatarShape: "round",
      buttonBgColor: "orange",
      font: "Playfair Display",
      round: "full",
      variant: "pop",
    },
  },
  {
    name: "web3enthusiast.bst",
    title: "Web3 Explorer",
    subtitle: "Navigating the Decentralized World",
    avatar: "https://yourlink.com/web3-avatar.png",
    bio: "Connecting people and communities across the Web3 ecosystem. Dive into my Web3 journey!",
    links: [
      {
        type: "simple link",
        title: "My Web3 Blog",
        url: "https://web3blog.yourlink.com",
        image: "",
        content: "",
        styles: {
          icon: "RiBankFill",
          size: "md",
          order: 0,
        },
      },
      {
        type: "twitter timeline",
        title: "Latest Tweets",
        url: "https://twitter.com/exampleuser",
        image: "",
        content: "",
        styles: {
          icon: "RiTwitterFill",
          size: "md",
          order: 1,
        },
      },
      {
        type: "nft gallery",
        title: "NFT Collection",
        url: "https://opensea.io/exampleuser",
        image: "https://yourlink.com/nft-collection.png",
        content: "",
        styles: {
          size: "sm",
          order: 2,
        },
      },
    ],
    wallets: {
      ETH: "0xExampleWalletAddress",
      Polygon: "0xExampleWalletAddress",
      Base: "0xExampleWalletAddress",
    },
    socials: {
      "com.linkedin": "https://linkedin.com/in/exampleuser",
      "com.discord": "https://discord.gg/exampleuser",
      "org.telegram": "https://t.me/exampleuser",
    },
    styles: {
      lightMode: true,
      bgColor: "linear-gradient(180deg, #1DA1F2 0%, #001f3f 100%)",
      avatarShape: "round",
      buttonBgColor: "blue",
      font: "DM Sans",
      round: "md",
      variant: "solid",
    },
  },
  {
    name: "cryptotrader.bst",
    title: "Crypto Trader",
    subtitle: "Buy Low, Sell High",
    avatar: "https://yourlink.com/trader-avatar.png",
    bio: "Daily updates, trading insights, and market analysis. Follow along for market moves and strategies!",
    links: [
      {
        type: "simple link",
        title: "Trading Blog",
        url: "https://tradingblog.yourlink.com",
        image: "",
        content: "",
        styles: {
          icon: "RiStockFill",
          size: "md",
          order: 0,
        },
      },
      {
        type: "token chart",
        title: "Market Charts",
        url: "https://tradingview.com/exampleuser",
        image: "",
        content: "",
        styles: {
          icon: "RiBarChartFill",
          size: "md",
          order: 1,
        },
      },
      {
        type: "donate button",
        title: "Support My Work",
        url: "",
        image: "",
        content: "Your support keeps this page going!",
        styles: {
          size: "md",
          eth: "0xExampleWalletAddress",
          order: 2,
        },
      },
    ],
    wallets: {
      BTC: "bc1qpvsvcfzvz59h02hcuvc8y8jj385r2mlhnkt654",
      ETH: "0xExampleWalletAddress",
    },
    socials: {
      "org.telegram": "https://t.me/exampleuser",
      "com.twitter": "https://twitter.com/exampleuser",
      "com.medium": "https://medium.com/@exampleuser",
    },
    styles: {
      lightMode: false,
      bgColor: "linear-gradient(180deg, #E74C3C 0%, #C0392B 100%)",
      avatarShape: "round",
      buttonBgColor: "red",
      font: "Audiowide",
      round: "none",
      variant: "solid",
    },
  },
  {
    name: "gamer.bst",
    title: "Pro Gamer",
    subtitle: "Level Up",
    avatar: "https://yourlink.com/gamer-avatar.png",
    bio: "Streaming my gaming adventures, tips, and epic highlights. Join me in the game!",
    links: [
      {
        type: "simple link",
        title: "Twitch Channel",
        url: "https://www.twitch.tv/exampleuser",
        image: "",
        content: "",
        styles: {
          icon: "RiTwitchFill",
          size: "md",
          order: 0,
        },
      },
      {
        type: "youtube video",
        title: "Latest Highlights",
        url: "https://youtu.be/gamehighlightvideo",
        image: "",
        content: "",
        styles: {
          icon: "RiYoutubeFill",
          size: "md",
          order: 1,
        },
      },
      {
        type: "simple link",
        title: "Game Store",
        url: "https://store.steampowered.com",
        image: "",
        content: "",
        styles: {
          icon: "RiGamepadFill",
          size: "md",
          order: 2,
        },
      },
      {
        type: "nft gallery",
        title: "Gaming NFT Collection",
        url: "https://opensea.io/gamingnfts",
        image: "",
        content: "",
        styles: {
          size: "sm",
          order: 3,
        },
      },
    ],
    wallets: {
      ETH: "0xExampleWalletAddress",
      Polygon: "0xExampleWalletAddress",
    },
    socials: {
      twitter: "https://twitter.com/exampleuser",
      discord: "https://discord.gg/exampleuser",
      instagram: "https://www.instagram.com/exampleuser",
    },
    styles: {
      lightMode: false,
      bgColor: "linear-gradient(180deg, #000000 0%, #3C3C3C 100%)",
      avatarShape: "round",
      buttonBgColor: "purple",
      font: "Luckiest Guy",
      round: "md",
      variant: "pop",
    },
  },
  {
    name: "freelancer.bst",
    title: "Freelance Designer",
    subtitle: "Bringing Ideas to Life",
    avatar: "https://yourlink.com/freelancer-avatar.png",
    bio: "Freelance graphic designer specializing in branding, UX/UI, and illustrations. Let's create something amazing!",
    links: [
      {
        type: "simple link",
        title: "Portfolio",
        url: "https://portfolio.yourlink.com",
        image: "",
        content: "",
        styles: {
          icon: "RiGalleryFill",
          size: "md",
          order: 0,
        },
      },
      {
        type: "pdf document",
        title: "Resume",
        url: "https://yourlink.com/resume.pdf",
        image: "",
        content: "",
        styles: {
          icon: "RiFileList3Fill",
          size: "md",
          order: 1,
        },
      },
      {
        type: "simple link",
        title: "Fiverr Profile",
        url: "https://www.fiverr.com/exampleuser",
        image: "",
        content: "",
        styles: {
          icon: "RiHandCoinFill",
          size: "md",
          order: 2,
        },
      },
      {
        type: "payment button",
        title: "Support My Work",
        url: "",
        image: "",
        content: "Thank you for supporting my freelance journey!",
        styles: {
          size: "md",
          order: 3,
          eth: "0xExampleWalletAddress",
        },
      },
    ],
    wallets: {
      ETH: "0xExampleWalletAddress",
      Polygon: "0xExampleWalletAddress",
    },
    socials: {
      linkedin: "https://linkedin.com/in/exampleuser",
      behance: "https://www.behance.net/exampleuser",
      instagram: "https://www.instagram.com/exampleuser",
    },
    styles: {
      lightMode: true,
      bgColor: "linear-gradient(180deg, #2ECC71 0%, #27AE60 100%)",
      avatarShape: "square",
      buttonBgColor: "green",
      font: "Poppins",
      round: "md",
      variant: "solid",
    },
  },
  {
    name: "developer.bst",
    title: "Web3 Developer",
    subtitle: "Building the Future of Web",
    avatar: "https://yourlink.com/developer-avatar.png",
    bio: "Experienced Web3 developer with a passion for decentralized applications and blockchain innovation.",
    links: [
      {
        type: "simple link",
        title: "GitHub",
        url: "https://github.com/exampleuser",
        image: "",
        content: "",
        styles: {
          icon: "RiGithubFill",
          size: "md",
          order: 0,
        },
      },
      {
        type: "simple link",
        title: "Portfolio",
        url: "https://portfolio.yourlink.com",
        image: "",
        content: "",
        styles: {
          icon: "RiCodeSSlashFill",
          size: "md",
          order: 1,
        },
      },
      {
        type: "tweet",
        title: "Latest Updates",
        url: "https://twitter.com/exampleuser/status/latesttweet",
        image: "",
        content: "",
        styles: {
          icon: "RiTwitterFill",
          size: "md",
          order: 2,
        },
      },
      {
        type: "embed",
        title: "Project Demo",
        url: "https://yourlink.com/projectdemo",
        image: "",
        content: "",
        styles: {
          size: "sm",
          order: 3,
        },
      },
    ],
    wallets: {
      ETH: "0xExampleWalletAddress",
      Polygon: "0xExampleWalletAddress",
      Solana: "ExampleSolanaAddress",
    },
    socials: {
      linkedin: "https://linkedin.com/in/exampleuser",
      twitter: "https://twitter.com/exampleuser",
      medium: "https://medium.com/@exampleuser",
    },
    styles: {
      lightMode: false,
      bgColor: "linear-gradient(180deg, #1ABC9C 0%, #16A085 100%)",
      avatarShape: "round",
      buttonBgColor: "teal",
      font: "Space Mono",
      round: "md",
      variant: "fill",
    },
  },
  {
    name: "nftcollector.bst",
    title: "NFT Enthusiast",
    subtitle: "Collecting Digital Art & Assets",
    avatar: "https://yourlink.com/nft-avatar.png",
    bio: "Exploring the metaverse, collecting rare digital assets, and sharing my NFT journey. Let's connect!",
    links: [
      {
        type: "nft gallery",
        title: "My NFT Collection",
        url: "https://opensea.io/exampleuser",
        image: "",
        content: "",
        styles: {
          size: "md",
          order: 0,
        },
      },
      {
        type: "simple link",
        title: "Metaverse Profile",
        url: "https://decentraland.org/exampleuser",
        image: "",
        content: "",
        styles: {
          icon: "RiLandscapeFill",
          size: "md",
          order: 1,
        },
      },
      {
        type: "tweet",
        title: "Latest NFT Acquisitions",
        url: "https://twitter.com/exampleuser/status/latesttweet",
        image: "",
        content: "",
        styles: {
          icon: "RiTwitterFill",
          size: "md",
          order: 2,
        },
      },
      {
        type: "donate button",
        title: "Support My NFT Journey",
        url: "",
        image: "",
        content: "Help me expand my NFT collection!",
        styles: {
          size: "md",
          eth: "0xExampleWalletAddress",
          order: 3,
        },
      },
    ],
    wallets: {
      ETH: "0xExampleWalletAddress",
      Polygon: "0xExampleWalletAddress",
    },
    socials: {
      twitter: "https://twitter.com/exampleuser",
      instagram: "https://www.instagram.com/exampleuser",
      opensea: "https://opensea.io/exampleuser",
    },
    styles: {
      lightMode: false,
      bgColor: "linear-gradient(180deg, #8E44AD 0%, #2C3E50 100%)",
      avatarShape: "round",
      buttonBgColor: "purple",
      font: "Audiowide",
      round: "full",
      variant: "border",
    },
  },
  {
    name: "simpleuser.bst",
    title: "Hello, I'm User",
    subtitle: "Exploring Web3",
    avatar: "https://yourlink.com/user-avatar.png",
    bio: "New to the world of Web3 and excited to learn more. Here are my favorite links and socials!",
    links: [
      {
        type: "simple link",
        title: "Personal Blog",
        url: "https://blog.yourlink.com",
        image: "",
        content: "",
        styles: {
          icon: "RiBookFill",
          size: "md",
          order: 0,
        },
      },
      {
        type: "simple link",
        title: "Portfolio",
        url: "https://portfolio.yourlink.com",
        image: "",
        content: "",
        styles: {
          icon: "RiGalleryFill",
          size: "md",
          order: 1,
        },
      },
      {
        type: "simple link",
        title: "Favorite Reads",
        url: "https://medium.com/@exampleuser",
        image: "",
        content: "",
        styles: {
          icon: "RiBookmarkFill",
          size: "md",
          order: 2,
        },
      },
    ],
    wallets: {
      ETH: "0xExampleWalletAddress",
    },
    socials: {
      twitter: "https://twitter.com/exampleuser",
      linkedin: "https://linkedin.com/in/exampleuser",
      medium: "https://medium.com/@exampleuser",
    },
    styles: {
      lightMode: true,
      bgColor: "linear-gradient(180deg, #3498DB 0%, #2980B9 100%)",
      avatarShape: "square",
      buttonBgColor: "blue",
      font: "Montserrat",
      round: "md",
      variant: "solid",
    },
  },
  {
    name: "digitalartist.bst",
    title: "Digital Artist",
    subtitle: "Creating Art in the Digital Space",
    avatar: "https://yourlink.com/artist-avatar.png",
    bio: "Passionate digital artist exploring colors, emotions, and the power of creativity. Welcome to my portfolio.",
    links: [
      {
        type: "image link",
        title: "Featured Artwork",
        url: "https://yourlink.com/artwork",
        image: "https://yourlink.com/featured-art.png",
        content: "",
        styles: {
          size: "sm",
          order: 0,
        },
      },
      {
        type: "simple link",
        title: "Portfolio",
        url: "https://portfolio.yourlink.com",
        image: "",
        content: "",
        styles: {
          icon: "RiGalleryFill",
          size: "md",
          order: 1,
        },
      },
      {
        type: "pdf document",
        title: "Artistic Resume",
        url: "https://yourlink.com/resume.pdf",
        image: "",
        content: "",
        styles: {
          icon: "RiFileList3Fill",
          size: "md",
          order: 2,
        },
      },
      {
        type: "simple link",
        title: "Instagram Art Page",
        url: "https://instagram.com/exampleuser",
        image: "",
        content: "",
        styles: {
          icon: "RiInstagramFill",
          size: "md",
          order: 3,
        },
      },
    ],
    wallets: {
      ETH: "0xExampleWalletAddress",
      Polygon: "0xExampleWalletAddress",
    },
    socials: {
      instagram: "https://www.instagram.com/exampleuser",
      dribbble: "https://dribbble.com/exampleuser",
      behance: "https://www.behance.net/exampleuser",
    },
    styles: {
      lightMode: false,
      bgColor: "linear-gradient(180deg, #FF6B6B 0%, #F07F5B 100%)",
      avatarShape: "round",
      buttonBgColor: "pink",
      font: "Playfair Display",
      round: "full",
      variant: "outline",
    },
  },
];
